// GLOBAL SETTINGS
http://mf.excess-project.eu:3030
Accept: application/json
--

# (1) Register a workflow linked to a user-defined experiment ID
#
#     Please note that it is not required to include a body message as
#     shown in the example below. If you want to retrieve, at a later stage,
#     some specific information with respect to the given experiment, plese
#     feel free to add them into the body. The body will not be parsed, and
#     thus it will be stored in the database as is.
#
# PUT /v1/dreamcloud/mf/workflows/:workflow_id/:expeirment_id
#
# Required:
# - workflow id, e.g. ms2i
# - experiment id, e.g. AVS-vzfnGMPeuCn4T2HZ
#
# Example request:
--
PUT /v1/dreamcloud/mf/workflows/ms2/AVS-vzfnGMPeuCn4T2HZ
{
    "application": "Molecular Dynamics Application",
    "author": "HLRS",
    "version": "v1"
}

# Example response for the above query
# {
#   "workflow": {
#     "id": "ms2",
#     "href": "http://mf.excess-project.eu:3030/v1/workflows/ms2"
#   },
#   "experiment": {
#     "id": "AVS-vzfnGMPeuCn4T2HZ",
#     "href": "http://mf.excess-project.eu:3030/v1/experiments/AVS-vzfnGMPeuCn4T2HZ?workflow=ms2"
#   }
# }

# (2) Add a deployment plan linked to the experiment
#
#     Please note that the body is not parsed, and thus it can contain
#     information required to your specific use case.
#
# PUT /v1/dreamcloud/mf/deployments/:workflow_id/:task_id/:platform_id/:experiment_id
#
# Required:
# - workflow id, e.g. ms2
# - task id, e.g. t2.1
# - platform id, e.g. test_cluster
# - experiment id, e.g. AVS-vzfnGMPeuCn4T2HZ
#
# Example request:
--
PUT /v1/dreamcloud/mf/deployments/ms2/t2.1/test_cluster/AVS-vzfnGMPeuCn4T2HZ
{
  "estimatedTime":217,
  "node":{
    "id":"node01",
    "cpus":[
      {
        "id":"cpu0",
        "cores":[
          {
            "id":"core0",
            "pwMode":100
          },
          {
            "id":"core1",
            "pwMode":100
          },
          {
            "id":"core2",
            "pwMode":100
          },
          {
            "id":"core3",
            "pwMode":100
          }
        ]
      }
    ]
  }
}

# Example response (includes URL for GET and the deployment id)
#
# {
#  "deployment_id": "da117e8171ae58b935a02a9768c21ce96ffd5f6e"
#  "predicted_time": 2017
#  "href": "http://mf.excess-project.eu:3030/v1/dreamcloud/mf/deployments/ms2/t2.1/test_cluster/da117e8171ae58b935a02a9768c21ce96ffd5f6e"
# }

# (3) POST new metric data linked to the given workflow and experiment
#
#     Please note that the body of this query has mandatory fields. The sender
#     has to provide the field '@timestamp', which has the following time
#     format: '%Y-%m-%dT%H:%M:%S.%f' (see example below). Furthermore, each
#     metric provided as a key-value pair will later be interpreted by the
#     statistics module. Thus, metric values have to be of type int or float.
#     If you want to add additional information, please feel free to do so.
#     The convention is to start non-metric keys with the prefix 'info_',
#     e.g., 'info_description'. The field 'platform' is not mandatory, but it
#     is advised to be used  if the deployment takes place across different
#     platform. This 'platform' field will then allow you later to filter
#     metric data based on the platform. Otherwise, you will not be able to
#     tell the source platform of the metric data.
#
# POST /v1/dreamclouf/mf/metrics/:workflow_id/:experiment_id?task=:task_id
#
# Required:
# - workflow id, e.g. ms2
# - experiment id, e.g. AVS-vzfnGMPeuCn4T2HZ
#
# Optional:
# - task id, e.g. t2.1
#
# Example request:
--
POST /v1/dreamcloud/mf/metrics/ms2/AVS-vzfnGMPeuCn4T2HZ?task_id=t2.1
{
  "@timestamp": "2016-05-11T12:36:11.283",
  "platform": "test_cluster",
  "loggedin_users": 4,
  "execution_time": 217,
  "info_description": "foobar"
}

# (4) GET all deployment plans for a given workflow, task, and platform
#
# GET /v1/dreamcloud/mf/deployments/:workflow_id/:task_id/:platform_id
#
# Required:
# - workflow id, e.g. ms2
# - task id, e.g. t2.1
# - platform id, e.g. test_cluster
#
# Example request:
--
GET /v1/dreamcloud/mf/deployments/ms2/t2.1/test_cluster

# (5) GET history information of experiments (includes experiments of all deployment plans)
#
# GET /v1/dreamcloud/mf/summary/:workflow_id/:task_id/:platform_id
#
# Required:
# - workflow id, e.g. ms2
# - task id, e.g. t2.1
# - platform id, e.g. test_cluster
#
# Example request:
--
GET /v1/dreamcloud/mf/summary/ms2/t2.1/test_cluster

# (6) GET history information of experiments of a given deployment plan
#
# GET /v1/dreamcloud/mf/summary/:workflow_id/:task_id/:platform_id/:deployment_id
#
# Required:
# - workflow id, e.g. ms2
# - task id, e.g. t2.1
# - platform id, e.g. test_cluster
# - deployment_id, e.g. 4e165a82309000fd5a6ab20c097b2e9f2ba5216d
#
# Example request:
--
GET /v1/dreamcloud/mf/summary/ms2/t2.1/test_cluster/4e165a82309000fd5a6ab20c097b2e9f2ba5216d

# (6) GET statistics for a given workflow and task filtered by custom fields
#
#     This query allows to get statistics for a given workflow and task id
#     across all experiments. End users can filter experiments by customs
#     fields such as 'info_channel' or 'platform'. Currently, only a single
#     field with exact matching is support for filtering. Users are currently
#     also requied to set the metric for which statistics shall be computed,
#     e.g., 'execution_time'.
#
# GET /v1/dreamcloud/mf/statistics/:workflow_id/:task_id
#
# Example request:
--
GET /v1/dreamcloud/mf/statistics/ms2/t2.1?filter=platform==test_cluster?metric=execution_time
GET /v1/dreamcloud/mf/statistics/ms2/t2.1?filter=info_channel=bbc1?metric=loggedin_users
